const CHROME_MESSAGE_TYPE = {
	GET_USER_SESSION: "GET_USER_SESSION",
	GET_EVENT_TYPES: "GET_EVENT_TYPES",
	GET_UPCOMING_BOOKINGS: "GET_UPCOMING_BOOKINGS",
	GET_PAST_BOOKINGS: "GET_PAST_BOOKINGS",
	MARK_SHOW_NOSHOW: "MARK_SHOW_NOSHOW",
};

export { CHROME_MESSAGE_TYPE };
